PRECISION = DOUBLE
PROFILE = FALSE

DEBUG = FALSE

DIM = 2
COMP = gnu
USE_CUDA = FALSE

USE_MPI = TRUE
USE_OMP = FALSE
USE_RAD = FALSE
USE_GRAV = TRUE
USE_POINTMASS = TRUE
USE_NEUTRINO = FALSE

CASTRO_HOME = ../../..
EOS_DIR     := gamma_law

NETWORK_DIR := general_null
NETWORK_INPUTS := csm.net
Opacity_dir = csm
Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro
