PRECISION = DOUBLE
PROFILE = FALSE

DEBUG = FALSE

DIM = 1
COMP = gnu

USE_MPI = TRUE
USE_OMP = FALSE
USE_RAD = TRUE
USE_NEUTRINO = FALSE

CASTRO_HOME = ../../..
EOS_DIR     := gamma_law

NETWORK_DIR := general_null
NETWORK_INPUTS := csm.net
Opacity_dir = csm
Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro
